// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAHRi6yOp02olrxE1lrRTfbGXHsXuESO0',
    appId: '1:510100294425:web:3ac8571b85a798247a1388',
    messagingSenderId: '510100294425',
    projectId: 'fruits-market-baf37',
    authDomain: 'fruits-market-baf37.firebaseapp.com',
    storageBucket: 'fruits-market-baf37.firebasestorage.app',
    measurementId: 'G-TC5CNV7FHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-Uzffrg9YUOo1YMdrHtBiR36dG0HsWa8',
    appId: '1:510100294425:android:ccde8649d1b27eda7a1388',
    messagingSenderId: '510100294425',
    projectId: 'fruits-market-baf37',
    storageBucket: 'fruits-market-baf37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiSNlwS7Ki7gOr40o0mbd1Fz5WpkXl3gg',
    appId: '1:510100294425:ios:3824e4c8d0a0e3967a1388',
    messagingSenderId: '510100294425',
    projectId: 'fruits-market-baf37',
    storageBucket: 'fruits-market-baf37.firebasestorage.app',
    iosBundleId: 'com.example.fruitsMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiSNlwS7Ki7gOr40o0mbd1Fz5WpkXl3gg',
    appId: '1:510100294425:ios:3824e4c8d0a0e3967a1388',
    messagingSenderId: '510100294425',
    projectId: 'fruits-market-baf37',
    storageBucket: 'fruits-market-baf37.firebasestorage.app',
    iosBundleId: 'com.example.fruitsMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAHRi6yOp02olrxE1lrRTfbGXHsXuESO0',
    appId: '1:510100294425:web:f105b6146859f0607a1388',
    messagingSenderId: '510100294425',
    projectId: 'fruits-market-baf37',
    authDomain: 'fruits-market-baf37.firebaseapp.com',
    storageBucket: 'fruits-market-baf37.firebasestorage.app',
    measurementId: 'G-6THPF9MJ7T',
  );
}
